debug: false

logging:
  level:
    root: error
#    org.springframework: DEBUG
    com.orange.oss.matomocfservice: DEBUG
    org.cloudfoundry.operations: DEBUG
#    org.springframework.cloud.servicebroker: DEBUG
#    com.jcraft.jsch: DEBUG
    liquibase: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
#    drop-first: true
