debug: false

logging:
  level:
    root: error
#    org.springframework: DEBUG
    com.orange.oss.matomocfservice: DEBUG
    org.cloudfoundry.operations: DEBUG
#    org.springframework.cloud.servicebroker: DEBUG
#    com.jcraft.jsch: DEBUG

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

